export interface PlayerPoolEntry {
  name: string;
  salary: number;
  amateur?: boolean;
}

// 2026 Masters field aligned to the official invitees list qualified as of 2026-04-02.
export const PLAYER_POOL: PlayerPoolEntry[] = [
  { name: "Scottie Scheffler", salary: 11800 },
  { name: "Rory McIlroy", salary: 11500 },
  { name: "Jon Rahm", salary: 11000 },
  { name: "Xander Schauffele", salary: 10800 },
  { name: "Cameron Young", salary: 10600 },
  { name: "Bryson DeChambeau", salary: 10400 },
  { name: "Collin Morikawa", salary: 10200 },
  { name: "Viktor Hovland", salary: 10000 },
  { name: "Ludvig Aberg", salary: 9900 },
  { name: "Hideki Matsuyama", salary: 9700 },
  { name: "Tommy Fleetwood", salary: 9500 },
  { name: "Justin Thomas", salary: 9300 },
  { name: "Jordan Spieth", salary: 9200 },
  { name: "Cameron Smith", salary: 9100 },
  { name: "Brooks Koepka", salary: 9000 },
  { name: "Shane Lowry", salary: 8900 },
  { name: "Brian Harman", salary: 8800 },
  { name: "Sam Burns", salary: 8700 },
  { name: "Patrick Cantlay", salary: 8600 },
  { name: "Patrick Reed", salary: 8600 },
  { name: "Wyndham Clark", salary: 8500 },
  { name: "Russell Henley", salary: 8500 },
  { name: "Corey Conners", salary: 8400 },
  { name: "Sungjae Im", salary: 8400 },
  { name: "Robert MacIntyre", salary: 8300 },
  { name: "Sepp Straka", salary: 8300 },
  { name: "Max Homa", salary: 8200 },
  { name: "Matt Fitzpatrick", salary: 8200 },
  { name: "Keegan Bradley", salary: 8100 },
  { name: "Tyrrell Hatton", salary: 8000 },
  { name: "Daniel Berger", salary: 7900 },
  { name: "Justin Rose", salary: 7900 },
  { name: "Jason Day", salary: 7800 },
  { name: "Dustin Johnson", salary: 7700 },
  { name: "Harris English", salary: 7600 },
  { name: "Gary Woodland", salary: 7600 },
  { name: "Akshay Bhatia", salary: 7500 },
  { name: "Maverick McNealy", salary: 7500 },
  { name: "Ryan Fox", salary: 7400 },
  { name: "Nick Taylor", salary: 7400 },
  { name: "Alex Noren", salary: 7400 },
  { name: "Si Woo Kim", salary: 7400 },
  { name: "J.J. Spaun", salary: 7400 },
  { name: "Davis Riley", salary: 7300 },
  { name: "Nicolai Hojgaard", salary: 7300 },
  { name: "Aaron Rai", salary: 7300 },
  { name: "Kurt Kitayama", salary: 7200 },
  { name: "Min Woo Lee", salary: 7200 },
  { name: "Chris Gotterup", salary: 7100 },
  { name: "Max Greyserman", salary: 7000 },
  { name: "Carlos Ortiz", salary: 7000 },
  { name: "Rasmus Hojgaard", salary: 6900 },
  { name: "Jake Knapp", salary: 6800 },
  { name: "Haotong Li", salary: 6700 },
  { name: "Matt McCarty", salary: 6600 },
  { name: "Andrew Novak", salary: 6600 },
  { name: "Sam Stevens", salary: 6500 },
  { name: "Ben Griffin", salary: 6500 },
  { name: "Tom McKibbin", salary: 6500 },
  { name: "Kristoffer Reitan", salary: 6500 },
  { name: "Rasmus Neergaard-Petersen", salary: 6400 },
  { name: "Harry Hall", salary: 6400 },
  { name: "Brian Campbell", salary: 6400 },
  { name: "Ryan Gerard", salary: 6400 },
  { name: "Michael Kim", salary: 6400 },
  { name: "Nicolas Echavarria", salary: 6400 },
  { name: "Casey Jarvis", salary: 6300 },
  { name: "Jacob Bridgeman", salary: 6300 },
  { name: "Michael Brennan", salary: 6300 },
  { name: "John Keefer", salary: 6200 },
  { name: "Sami Valimaki", salary: 6200 },
  { name: "Marco Penge", salary: 6000 },
  { name: "Aldrich Potgieter", salary: 5900 },
  { name: "Sergio Garcia", salary: 5900 },
  { name: "Adam Scott", salary: 5800 },
  { name: "Bubba Watson", salary: 5700 },
  { name: "Angel Cabrera", salary: 5600 },
  { name: "Danny Willett", salary: 5600 },
  { name: "Naoyuki Kataoka", salary: 5500 },
  { name: "Zach Johnson", salary: 5500 },
  { name: "Charl Schwartzel", salary: 5400 },
  { name: "Vijay Singh", salary: 5300 },
  { name: "Mike Weir", salary: 5300 },
  { name: "Fred Couples", salary: 5200 },
  { name: "Jose Maria Olazabal", salary: 5200 },
  { name: "Ethan Fang", salary: 5000, amateur: true },
  { name: "Jackson Herrington", salary: 5000, amateur: true },
  { name: "Brandon Holtz", salary: 5000, amateur: true },
  { name: "Mason Howell", salary: 5000, amateur: true },
  { name: "Fifa Laopakdee", salary: 5000, amateur: true },
  { name: "Mateo Pulcini", salary: 5000, amateur: true },
];
